config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", include("tuxbot.pages.urls", namespace="pages")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tuxbot.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tuxbot/pages/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView

from tuxbot.pages.views import HomeView, WikiView

app_name = "pages"
urlpatterns = [
    path("", view=HomeView.as_view(), name="home"),

    path("wiki/", view=WikiView.as_view(), name="wiki"),
    re_path(r"^wiki/(?P<path>[a-zA-Z0-9/\.~\-]+)$", view=WikiView.as_view(),
            name="wiki"),

    path("support/",
         view=RedirectView.as_view(url='https://discord.gg/URKy7yd'),
         name="support"),
    path("add/",
         view=RedirectView.as_view(url='https://discord.com/oauth2/authorize?client_id=301062143942590465&scope=bot&permissions=271969351'),
         name="add"),
    path("sources/",
         view=RedirectView.as_view(url='https://github.com/Rom1-J/tuxbot-bot'),
         name="sources"),
]

tuxbot/users/urls.py
from django.urls import path

from tuxbot.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

tuxbot/pages/models.py
from django.db import models

tuxbot/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Tuxbot."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

tuxbot/pages/forms.py
from django.forms import ModelForm

tuxbot/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

tuxbot/pages/views.py
from django.conf import settings
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View

template_path = "pages/"


class HomeView(View):
    template_name = template_path + "home.html"

    def get(self, request: WSGIRequest):
        return render(request, self.template_name)


class WikiView(View):
    template_name = template_path + "wiki/build/"

    def get(self, request: WSGIRequest, path=None):
        file_path = settings.ROOT_DIR / "tuxbot/templates"
        content_type = "text/html"

        if path is None:
            file_path /= self.template_name + "index.html"
        elif len(path.split('.')) == 1:
            file_path /= self.template_name + path + "/index.html"
        else:
            file_path /= self.template_name + path

            if (ext := path.split('.')[-1]) == "js":
                content_type = f"text/javascript"
            elif ext in ["svg", "png", "jpg", "jpeg"]:
                content_type = f"image/{ext}"
            else:
                content_type = f"text/{ext}"

        with open(file_path, "rb") as f:
            return HttpResponse(f.read(), content_type=content_type)

tuxbot/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

tuxbot/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

tuxbot/templates/layouts/parts/footer.html
{% load static %}
{% load i18n %}


<footer class="uk-padding-remove-bottom uk-section-secondary">
    <div class="uk-padding uk-flex">
        <div class="uk-container uk-width">
            <div class="uk-column-1-2@s">
                <div>
                    <span class="uk-h2 uk-text-uppercase">Tuxbot</span>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.<br>
                        Ducimus eius itaque nam quam suscipit. Eius excepturi exercitationem ipsa omnis quas? Ab ad
                        corporis cum</p>
                </div>
                <div class="uk-text-right@s">
                    <u class="uk-text-muted">{% trans "Get Help" %}</u>


                    <ul class="uk-list">
                        <li><a href="{% url 'pages:wiki' %}">{% trans "Read the Docs" %}</a></li>
                        <li><a href="{% url 'pages:support' %}">{% trans "Support server" %}</a></li>
                    </ul>

                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        {% get_current_language as LANGUAGE_CODE %}
                        {% if LANGUAGE_CODE == 'en' %}
                            <button type="submit" style="background: transparent; border: none">
                                <img src="{% static 'images/icons/fr.svg' %}" alt="fr" width="18">
                            </button>
                            <input type="hidden" name="language" value="fr">
                        {% else %}
                            <button type="submit" style="background: transparent; border: none">
                                <img src="{% static 'images/icons/en.svg' %}" alt="en" width="18">
                            </button>
                            <input type="hidden" name="language" value="en">
                        {% endif %}
                    </form>

                </div>
            </div>
            <hr>
            <div class="uk-column-1-2@s">
                <div class="uk-text-left@s uk-text-center">
                    <span class="uk-text-small uk-text-muted">© {% now "Y" %}
                        <a href="https://gnous.eu" target="_blank" class="uk-link">GnousEU</a>
                        | {% trans "Designed and created by" %}
                    </span>
                    <a class="uk-text-small uk-link" href="https://github.com/Rom1-J" target="_blank">Romain J.</a>

                    <span class="uk-text-small uk-text-muted"> | {% trans "Built with" %} </span>
                    <a href="https://getuikit.com" target="_blank" uk-tooltip="UIKit"
                       class="uk-link" uk-icon="icon: uikit">

                    </a>
                </div>
                <div class="uk-text-right@s uk-margin-top">
                    <a href="{% url "pages:add" %}" class="uk-button uk-button-primary uk-width uk-width-auto@s"><span
                            uk-icon="icon: discord"></span> {% trans "Add to Discord" %}</a>
                </div>
            </div>
        </div>
    </div>
</footer>

tuxbot/templates/layouts/parts/navbar.html
{% load static %}
{% load i18n %}
<header>
    <nav class="uk-navbar-container uk-navbar-transparent" uk-navbar>
        <div class="uk-navbar-left">
            <ul class="uk-navbar-nav uk-navbar-nav">
                <li {% if request.resolver_match.url_name == 'home' %} class="uk-active" {% endif %}>
                    <a href="{% url 'pages:home' %}">Tuxbot</a>
                </li>
                <li {% if request.resolver_match.url_name == 'wiki' %} class="uk-active" {% endif %}>
                    <a href="{% url 'pages:wiki' %}">{% trans "wiki" %}</a>
                </li>
                <li {% if request.resolver_match.url_name == 'support' %} class="uk-active" {% endif %}>
                    <a href="{% url 'pages:support' %}">{% trans "support" %}</a>
                </li>
                <li {% if request.resolver_match.url_name == 'support' %} class="uk-active" {% endif %}>
                    <a href="{% url 'pages:sources' %}">{% trans "sources" %}</a>
                </li>
            </ul>

        </div>
        <div class="uk-navbar-right">
            <ul class="uk-navbar-nav uk-navbar-nav">
                {% if not request.user.is_authenticated %}
                    <li {% if request.resolver_match.url_name == 'account_login' %} class="uk-active" {% endif %}>
                        <a href="#" uk-icon="icon: discord; ratio: 2"></a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'groups:home' %}">{% trans "My groups" %}</a>
                    </li>
                    <li>
                        <a href="#">{% trans "My profile" %}</a>
                        <div class="uk-navbar-dropdown">
                            <ul class="uk-nav uk-navbar-dropdown-nav">
                                <li {% if request.resolver_match.url_name == 'update' %} class="uk-active" {% endif %}>
                                    <a href="{% url 'users:update' %}">{% trans 'Settings' %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'account_logout' %}" class="uk-text-danger">{% trans 'Logout' %}</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>