config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", include("tuxbot.pages.urls", namespace="pages")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tuxbot.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tuxbot_web/pages/urls.py
from django.urls import path

from tuxbot_web.pages.views import HomeView, SourcesView, ContactView

app_name = "pages"
urlpatterns = [
    path("", view=HomeView.as_view(), name="home"),
    # path("wiki/", view=user_detail_view, name="wiki"),
    path("sources/", view=SourcesView.as_view(), name="sources"),
    path("contact/", view=ContactView.as_view(), name="contact"),
]

tuxbot_web/users/urls.py
from django.urls import path

from tuxbot_web.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

tuxbot_web/pages/models.py
from django.db import models
from django.db.models import (
    CharField,
    EmailField,
    TextField,
    DateTimeField,
    BooleanField,
)
from django.db.models.fields import AutoField
from django.utils.translation import gettext_lazy as _


class Contact(models.Model):
    id = AutoField(primary_key=True)
    name = CharField(_("Name"), blank=False, max_length=255)
    email = EmailField(_("Email"), blank=False)
    message = TextField(_("Message"), blank=False)

    created_at = DateTimeField(auto_now_add=True)

    read = BooleanField(_("Read"), default=False)
    answered = BooleanField(_("Answered"), default=False)

tuxbot_web/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Tuxbot Web Admin."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

tuxbot_web/pages/forms.py
from django.forms import ModelForm

from django.utils.translation import gettext_lazy as _
from tuxbot_web.pages.models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ["name", "email", "message"]

        labels = {
            "name": _("Your name"),
            "email": _("Your email"),
            "message": _("Your message"),
        }

    def is_valid(self):
        result = super().is_valid()
        # loop on *all* fields if key '__all__' found else only on errors:
        for x in self.fields if "__all__" in self.errors else self.errors:
            attrs = self.fields[x].widget.attrs
            attrs.update({"class": attrs.get("class", "") + " form-error"})
        return result

tuxbot_web/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

tuxbot_web/pages/views.py
from django.contrib import messages
from django.core.handlers.wsgi import WSGIRequest
from django.utils.translation import gettext_lazy as _
from django.shortcuts import render
from django.views.generic import View

from tuxbot_web.pages.forms import ContactForm

template_path = "pages/"


class HomeView(View):
    template_name = template_path + "home.html"

    def get(self, request: WSGIRequest):
        return render(request, self.template_name)


class SourcesView(View):
    template_name = template_path + "sources.html"

    def get(self, request: WSGIRequest):
        return render(request, self.template_name)


class ContactView(View):
    form_class = ContactForm
    template_name = template_path + "contact.html"

    def get(self, request: WSGIRequest):
        form = self.form_class(initial={"name": self.request.user.username})

        return render(request, self.template_name, {"form": form})

    def post(self, request: WSGIRequest):
        form = self.form_class(request.POST)
        status = 200

        if form.is_valid():
            messages.add_message(
                request, messages.SUCCESS, _("Message sent successfully")
            )
            form.save()

            form = self.form_class(
                initial={"name": self.request.user.username}
            )
        else:
            status = 400

        return render(
            request, self.template_name, {"form": form}, status=status
        )

tuxbot_web/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import (
    ListModelMixin,
    RetrieveModelMixin,
    UpdateModelMixin,
)
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(
    RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet
):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

tuxbot_web/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.request.user.username}
        )

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.request.user.username}
        )


user_redirect_view = UserRedirectView.as_view()

tuxbot_web/templates/layouts/parts/footer.html
{% load static %}
{% load i18n %}
<footer class="footer">
	<div class="footer-row">
		<div class="footer-description">
			<span class="footer-title">TUXBOT</span>
			<p class="footer-copyright">© {% now 'Y' %} GnousEU | {% trans 'Created by' %} <a href="https://github.com/Rom1-J" target="_blank">Romain J.</a> & <a href="https://github.com/outout14" target="_blank">Outout</a></p>
		</div>
		<div class="footer-links">
			<div class="footer-column">
				<a href="#" class="footer-link">{% trans 'Wiki' %}</a>
				<a href="{% url 'pages:sources' %}" class="footer-link">{% trans 'Sources' %}</a>
				<a href="https://discord.gg/URKy7yd" class="footer-link">{% trans 'Support Server' %}</a>
			</div>
			<div class="footer-column">
				<a href="{% url 'pages:contact' %}" class="footer-link">{% trans 'Contact' %}</a>
				<a href="#" class="footer-link">{% trans 'Terms' %}</a>
				<a href="#" class="footer-link">{% trans 'Privacy Policy' %}</a>
				<div class="footer-dropdown">
					<a href="#" class="footer-link">
						{% get_current_language as LANGUAGE_CODE %}
						{% get_language_info for LANGUAGE_CODE as l %}
						<img class="icon icon-small margin-clear" src="{% static 'images/icons/flags/'|add:l.code|add:'.svg' %}" alt loading="lazy">
						<span>{{ l.name_translated }}</span>
						<svg class="icon icon-small margin-clear">
							<use href="{% static 'images/icons/sort.svg' %}#sort"></use>
						</svg>
					</a>
					<ul class="footer-dropdown-nav">
						{% for language in LANGUAGES %}
							<li>
								<form action="{% url "set_language" %}" method="post">
									{% csrf_token %}
									<button type="submit" {% if LANGUAGE_CODE == language.0 %} class="active" {% endif %}>
										<img class="icon icon-small margin-clear" src="{% static 'images/icons/flags/'|add:language.0|add:'.svg' %}" alt loading="lazy">
										<span class="margin-small-left">{{ language.1 }}</span>
									</button>
									<input name="language" value="{{ language.0 }}" type="hidden">
								</form>
							</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-row">
		<div class="footer-sub-description">
			<h2 class="footer-title">Here is the place to the main argument</h2>
			<p class="footer-subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
		</div>
		<div>
			<button type="button" class="button button-primary button-large"><img class="icon icon-small" src="{% static 'images/icons/social/discord.svg' %}" alt="Tuxbot">{% trans 'Add to Discord' %}</button>
		</div>
	</div>
</footer>

tuxbot_web/templates/layouts/parts/navbar.html
{% load static %}
{% load i18n %}
<header class="navbar">
	<div class="navbar-full">
		<a href="{% url 'pages:home' %}" class="navbar-title">TUXBOT</a>
		<nav class="navbar-left" aria-label="Related links">
			<ul class="navbar-nav">
				<li {% if request.resolver_match.url_name == 'wiki' %} class="active" {% endif %}>
					<a href="#">{% trans 'Wiki' %}</a>
					<div class="navbar-dropdown">
						<ul class="navbar-dropdown-nav">
							<li><a href="#">Admin</a></li>
							<li><a href="#">ID</a></li>
							<li><a href="#">Linux</a></li>
							<li><a href="#">Network</a></li>
							<li><a href="#">Poll</a></li>
							<li><a href="#">Utils</a></li>
							<li><a href="#">Vocal</a></li>
							<li><a href="#">World</a></li>
						</ul>
					</div>
				</li>
				<li {% if request.resolver_match.url_name == 'sources' %} class="active" {% endif %}>
					<a href="{% url 'pages:sources' %}">{% trans 'Sources' %}</a>
				</li>
				<li {% if request.resolver_match.url_name == 'contact' %} class="active" {% endif %}>
					<a href="{% url 'pages:contact' %}">{% trans 'Contact' %}</a>
				</li>
				<li>
					<a href="https://discord.gg/URKy7yd" target="_blank">{% trans 'Support Server' %}</a>
				</li>
			</ul>
		</nav>
		<nav class="navbar-right" aria-label="Profile links">
			<ul class="navbar-nav">
				{% if not request.user.is_authenticated %}
					<li>
						<a href="{% url 'account_login' %}" class="button button-link">{% trans "Login" %}</a>
					</li>
				{% else %}
					<li>
						<a href="#">
							<img alt src="https://cdn.discordapp.com/avatars/269156684155453451/ff06e3b4ebd8ac5b4cad78a0a968e95a.png?size=32">
							<span>{{ request.user.username }}</span>
							<svg class="icon icon-small margin-clear">
								<use href="{% static 'images/icons/sort.svg' %}#sort"></use>
							</svg>
						</a>
						<div class="navbar-dropdown">
							<ul class="navbar-dropdown-nav">
								<li>
									<a href="{% url 'users:detail' request.user.username %}">{% trans 'My Servers' %}</a>
								</li>
								<li>
									<a href="#">{% trans 'Settings' %}</a>
								</li>
								<li>
									<a href="{% url 'account_logout' %}" class="text-danger">{% trans 'Logout' %}</a>
								</li>
							</ul>
						</div>
					</li>
				{% endif %}
			</ul>
		</nav>
	</div>

	<div class="navbar-responsive">
		<a class="navbar-hamburger" href="#">
			<div></div>
			<div></div>
			<div></div>
		</a>
		<a href="{% url 'pages:home' %}" class="navbar-title">TUXBOT</a>

		<div class="navbar-profile">
			{% if not request.user.is_authenticated %}
				<a href="{% url 'account_login' %}" class="button button-link padding-clear">{% trans "Login" %}</a>
			{% else %}
				<a href="#">
					<img alt src="https://cdn.discordapp.com/avatars/269156684155453451/ff06e3b4ebd8ac5b4cad78a0a968e95a.png?size=32">
					<svg class="icon icon-small margin-clear">
						<use href="{% static 'images/icons/sort.svg' %}#sort"></use>
					</svg>
				</a>
				<div class="navbar-dropdown">
					<ul class="navbar-dropdown-nav">
						<li>
							<a href="{% url 'users:detail' request.user.username %}">{% trans 'My Servers' %}</a>
						</li>
						<li>
							<a href="#">{% trans 'Settings' %}</a>
						</li>
						<li>
							<a href="{% url 'account_logout' %}" class="text-danger">{% trans 'Logout' %}</a>
						</li>
					</ul>
				</div>
			{% endif %}
		</div>

		<div class="navbar-break"></div>

		<div class="navbar-sidebar">
			<ul class="navbar-nav">
				<li {% if request.resolver_match.url_name == 'wiki' %} class="active" {% endif %}>
					<a href="#">{% trans 'Wiki' %}</a>
				</li>
				<li {% if request.resolver_match.url_name == 'sources' %} class="active" {% endif %}>
					<a href="{% url 'pages:sources' %}">{% trans 'Sources' %}</a>
				</li>
				<li {% if request.resolver_match.url_name == 'contact' %} class="active" {% endif %}>
					<a href="{% url 'pages:contact' %}">{% trans 'Contact' %}</a>
				</li>
				<li>
					<a href="https://discord.gg/URKy7yd" target="_blank">{% trans 'Support Server' %}</a>
				</li>
			</ul>
		</div>
	</div>
</header>

tuxbot_web/templates/layouts/parts/notification.html
{% load static %}
<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
	<svg class="icon icon-small icon-success">
		<use href="{% static 'images/icons/check.svg' %}#check"></use>
	</svg>
	<div>
		<strong>{{ message }}</strong>
	</div>
</div>